services:
  app:
    build: .
    command:
      /usr/local/bin/wait-for-it.sh db:5432 -- python3 vision_park/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres:14.8-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres_local"
    expose:
      - "5432"
    ports:
      - "5433:5432"
    restart: always
