services:
  app:
    build: .
    command:
      /bin/sh -c "/usr/local/bin/wait-for-it.sh db:5432 -- python3 /app/vision_park/manage.py migrate --noinput && python3 /app/vision_park/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres:14.8-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "vision_park_db"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always

  bot:
    build: .
    command:
      sh -c "python3 /app/aiogram/run.py"
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: always
