# Generated by Django 5.0.6 on 2024-05-08 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
